CREATE PROCEDURE XXBCM_ORDER_MGT_MIGRATION
AS
BEGIN
    -- STEP 1: INSERT SUPPLIERS DATA
    INSERT INTO SUPPLIERS (SUPPLIER_NAME, SUPPLIER_CONTACT_NAME, SUPPLIER_ADDRESS, SUPPLIER_CONTACT_NUMBER, SUPPLIER_EMAIL)
    SELECT DISTINCT SUPPLIER_NAME, SUPP_CONTACT_NAME, REPLACE(SUPP_ADDRESS, '-,', '') AS SUPP_ADDRESS, REPLACE(REPLACE(REPLACE(SUPP_CONTACT_NUMBER, 'o', '0'), 'S', '5'), '.', '') AS SUPP_CONTACT_NUMBER, SUPP_EMAIL
    FROM XXBCM_ORDER_MGT;

    -- STEP 2: INSERT ORDERS DATA
    INSERT INTO ORDERS (ORDER_REF, ORDER_DATE, SUPPLIER_ID, INVOICE_REF, ORDER_TOTAL_AMOUNT, ORDER_LINE_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS)
    SELECT ORDER_REF, CONVERT(DATE, ORDER_DATE, 103) AS ORDER_DATE, S.SUPPLIER_ID, INVOICE_REFERENCE,
	ISNULL(CAST(REPLACE(ORDER_TOTAL_AMOUNT, ',', '') AS DECIMAL(10, 2)),0 ) AS  ORDER_TOTAL_AMOUNT,
	ISNULL(CAST(REPLACE(REPLACE(REPLACE(REPLACE(ORDER_LINE_AMOUNT, ',', ''), 'S', '5'),'o', '0'), 'I', '1')  AS DECIMAL(10, 2)), 0) AS ORDER_LINE_AMOUNT,
	ORDER_DESCRIPTION, ORDER_STATUS
    FROM XXBCM_ORDER_MGT O
    INNER JOIN SUPPLIERS S ON O.SUPPLIER_NAME = S.SUPPLIER_NAME;

    -- STEP 3: INSERT INVOICES DATA
    INSERT INTO INVOICES (INVOICE_REF, INVOICE_DATE, ORDER_ID, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION)
    SELECT INVOICE_REFERENCE,
	CONVERT(DATE, INVOICE_DATE, 103) AS INVOICE_DATE,
	O.ORDER_ID, INVOICE_STATUS, INVOICE_HOLD_REASON,
	ISNULL(CAST(REPLACE(REPLACE(REPLACE(REPLACE(INVOICE_AMOUNT, ',', ''), 'S', '5'),'o', '0'), 'I', '1')  AS DECIMAL(10, 2)), 0) AS INVOICE_AMOUNT,
	INVOICE_DESCRIPTION
    FROM XXBCM_ORDER_MGT X
    INNER JOIN ORDERS O ON X.ORDER_REF = O.ORDER_REF AND X.INVOICE_REFERENCE = O.INVOICE_REF AND X.ORDER_DESCRIPTION = O.ORDER_DESCRIPTION
	ORDER BY O.ORDER_ID
END;
