CREATE TABLE SUPPLIERS (
    SUPPLIER_ID INT PRIMARY KEY IDENTITY(1,1),
    SUPPLIER_NAME VARCHAR(255) NOT NULL,
    SUPPLIER_CONTACT_NAME VARCHAR(255),
    SUPPLIER_ADDRESS VARCHAR(255),
    SUPPLIER_CONTACT_NUMBER VARCHAR(255),
    SUPPLIER_EMAIL VARCHAR(255)
);

CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY IDENTITY(1,1),
    ORDER_REF VARCHAR(20) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    SUPPLIER_ID INT NOT NULL,
	INVOICE_REF VARCHAR(20),
    ORDER_TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL,
	ORDER_LINE_AMOUNT DECIMAL(10, 2) NOT NULL,
    ORDER_DESCRIPTION VARCHAR(255),
    ORDER_STATUS VARCHAR(20) NOT NULL,
    CONSTRAINT FK_SUPPLIER
        FOREIGN KEY (SUPPLIER_ID)
        REFERENCES SUPPLIERS (SUPPLIER_ID)
);

CREATE TABLE INVOICES (
    INVOICE_ID INT PRIMARY KEY IDENTITY(1,1),
    INVOICE_REF VARCHAR(20) NOT NULL,
    INVOICE_DATE DATE NOT NULL,
    ORDER_ID INT NOT NULL,
    INVOICE_STATUS VARCHAR(20) NOT NULL,
    INVOICE_HOLD_REASON VARCHAR(255),
    INVOICE_AMOUNT DECIMAL(10, 2) NOT NULL,
    INVOICE_DESCRIPTION VARCHAR(255),
    CONSTRAINT FK_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS (ORDER_ID)
);
